### PR TITLE
use the right $ as UMD Module

### PR DESCRIPTION
**Pull request by BowlingX**
Hey :)
thank you first for this plugin, it makes things a lot easier while dealing with DFP :).
I changed the way the module loads, because the current UMD implementation is not correct.

```
(function($, window, undefined)(window.jQuery....)
````

The $ shadows the underlying implementation and so a global $ is always used by the plugin (which is not available when loaded with a module loader). I changed it in a way that if a module loader is in scope all dependencies will be resolved first and then delegated to your implementation.

Best
David

### CODE REVIEW

**Comment by coop182** [comment]
Thanks for this... I will merge once I get a chance to look at the change properly... github is giving me a really messy diff!

**Comment by BowlingX** [comment]
Sorry for the diff :/, I had to move everything and restore the intention. Thanks for looking.

**Comment by coop182** [comment]
There we go... thanks for the fix!

**Comment by HeadOnAPlate** [comment]
Just an fyi with regards to the messy diff: if you add "?w=1" to the url, whitespace changes are ignored and it clears it up quite nicely.

**Pull request merged**
